name: "S3 Setup"

on:
  push:
    branches:
      - main

jobs:
  setup-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check if S3 Bucket Exists
        id: check-bucket
        continue-on-error: true
        run: |
          BUCKET_NAME="my-terraform-storage-bucket"
          if aws s3 ls "s3://$BUCKET_NAME" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "BUCKET_EXISTS=false" >> $GITHUB_ENV
          else
            echo "BUCKET_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: Create S3 Bucket If Not Exists
        if: env.BUCKET_EXISTS == 'false'
        run: |
          aws s3 mb s3://my-terraform-storage-bucket
          echo "S3 bucket created."
