name: Terraform Apply

on:
  push:
    branches:
      - main  # Runs when you push to the 'main' branch, adjust if needed

jobs:
  terraform:
    runs-on: ubuntu-latest  # The OS where the job will run (can use other environments like windows-latest)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your code so the runner can use it

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Specify the version of Terraform you want to use

    - name: Download Terraform Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan  # Name of the artifact you're downloading
        path: ./terraform-plan  # Directory where the artifact will be saved

    - name: Terraform Apply
      run: terraform apply -auto-approve ./terraform-plan/terraform.tfplan  # Apply the Terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secrets for AWS credentials
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1  # Set the region (modify if needed)
