name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .  # ✅ Use root directory

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug - Check Directory Structure
        run: |
          echo "Current Directory: $(pwd)"
          ls -al

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        run: |
          echo "Running terraform init in:"
          pwd
          ls -al
          terraform init

      - name: Plan Terraform
        run: terraform plan
