name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 1: Temporarily Remove Backend to Allow S3 Creation
      - name: Step 1 - Create S3 Bucket Without Backend
        run: |
          echo "Disabling backend to create S3 bucket..."
          mv backend.tf backend.tf.disabled # Temporarily disable backend config
          terraform init
          terraform apply -target=aws_s3_bucket.terraform_state -auto-approve

      # Step 2: Restore Backend and Reinitialize
      - name: Step 2 - Enable Backend and Reinitialize
        run: |
          echo "Re-enabling backend..."
          mv backend.tf.disabled backend.tf # Restore backend config
          terraform init -force-copy

      # Step 3: Terraform Plan
      - name: Step 3 - Terraform Plan
        run: terraform plan
