name: Terraform Apply

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch, you can change it based on your workflow

jobs:
  terraform:
    runs-on: ubuntu-latest  # You can use other runners, like windows-latest or macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out your repository code

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Specify the Terraform version you want to use

    - name: Download Terraform Plan Artifact
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan  # This is the artifact name from the upload step
        path: ./terraform-plan  # Path where it will be saved

    - name: Terraform Init
      run: terraform init  # Initialize the Terraform working directory

    - name: Terraform Apply
      run: terraform apply -auto-approve ./terraform-plan/terraform.tfplan  # Apply the plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Assuming you have AWS credentials in your GitHub secrets
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1  # Update the region if needed

